# Generated by Django 6.0.4 on 2026-04-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
