# Generated by Django 6.0.4 on 2026-04-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('dt_agenda', models.DateField()),
                ('hr_agenda', models.TimeField()),
                ('id_agendamento', models.ForeignKey(blank=True, db_column='id_agendamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.agendamento')),
                ('id_profissional', models.ForeignKey(db_column='id_profissional', on_delete=django.db.models.deletion.CASCADE, to='profissional.profissional')),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
