# Generated by Django 6.0.4 on 2026-04-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('ativo', models.CharField(default='1', max_length=1)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('id_profissional', models.ForeignKey(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissional.profissional')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
