# Generated by Django 6.0.4 on 2026-04-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('vlr_servico', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duracao_em_min', models.IntegerField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
    ]
