# Generated by Django 6.0.4 on 2026-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
