# Generated by Django 6.0.4 on 2026-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
