# Generated by Django 6.0.4 on 2026-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('dt_criacao', models.DateField()),
                ('tipo_empresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
